title: GitKraken Palenight Theme
description: A Palenight theme for GitKraken

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social_links:
    github:  samuelsandri

theme: minima

plugins:
 - jekyll-seo-tag
